// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa7o9oUepycM3ACew76q8EXcuvkHDhr_o',
    appId: '1:467851200471:android:319e835852035be317ad92',
    messagingSenderId: '467851200471',
    projectId: 'lucky-table',
    storageBucket: 'lucky-table.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXDRn_-IexMAeDy4X8Q5SJ8Xljb_mGCfM',
    appId: '1:467851200471:ios:f2adfffb1163132a17ad92',
    messagingSenderId: '467851200471',
    projectId: 'lucky-table',
    storageBucket: 'lucky-table.appspot.com',
    androidClientId: '467851200471-515vb5mr724vc4i61f24krkic0b4mrbe.apps.googleusercontent.com',
    iosClientId: '467851200471-pu89aturrt09v98565294a16rbi9eac2.apps.googleusercontent.com',
    iosBundleId: 'com.trdsoft.lucky-table',
  );
}
